version: "2.2"
services:
  interface: 
    build: ./developers-frontend
    ports:
      - "3000:3000"
    stdin_open: true
    depends_on: 
      - web
  web:
    build: ./developers-backend
    ports:
      - "3001:3001"
    environment:
      MONGODB_URI: 'mongodb://mongo:27017/developers'
      PORT: 3001
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27017:27017"